# Generated by Django 2.0.6 on 2018-06-10 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('charge', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('charge_number', models.IntegerField()),
                ('total_charges', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('file_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.Category')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.Files'),
        ),
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.Names'),
        ),
    ]
