# Generated by Django 2.0.6 on 2018-08-19 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('charge', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('charge_number', models.IntegerField()),
                ('total_charges', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('cat', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='expense.Category')),
            ],
            options={
                'verbose_name_plural': 'names',
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.Names'),
        ),
    ]
