# Generated by Django 2.0.6 on 2018-08-19 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expense', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_id', models.CharField(max_length=10)),
                ('last_4', models.CharField(max_length=4)),
                ('card_type', models.CharField(max_length=250)),
                ('debit_date', models.IntegerField()),
                ('owner_name', models.CharField(max_length=250)),
                ('is_effective', models.BooleanField()),
                ('bank_code', models.IntegerField()),
                ('bank_branch', models.IntegerField()),
                ('bank_account', models.IntegerField()),
                ('bank_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CalExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visacal.CalCard')),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expense.Expense')),
            ],
        ),
        migrations.CreateModel(
            name='CalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('token', models.CharField(max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visacal.CalUser'),
        ),
    ]
